"""Declarative base, shared column types, and the naming convention.

Two decisions here are worth stating, because both are hard to change later.

**Everything lives in one named schema** (``browser`` by default), not in
``public``. A named schema lets this application share a database with others
without a table-name collision, and makes "drop everything this app owns" a
single statement -- which is what the test harness relies on.

**Constraints are named by convention.** Alembic can only emit
``ALTER TABLE ... DROP CONSTRAINT`` for a constraint it can name, and Postgres
autogenerates names that differ from SQLAlchemy's guesses. Without the
convention below, autogenerated downgrades silently produce SQL that fails on
the day you need it.
"""

from __future__ import annotations

import os
import uuid
from datetime import datetime, timezone
from pathlib import Path

from sqlalchemy import DateTime, MetaData, String
from sqlalchemy.orm import DeclarativeBase, mapped_column

def _schema() -> str:
    """The schema every table lives in, resolved at import time.

    SQLAlchemy binds the schema into ``MetaData`` when the model classes are
    defined, which happens long before any ``Settings`` object exists. So this
    cannot come from ``Settings`` -- it has to be read here, first.

    That used to mean reading only ``os.environ``, and it made ``DB_SCHEMA`` the
    one setting that did not work from ``.env``: pydantic-settings loads that
    file when ``Settings()`` is constructed, by which point the models are
    already built for the wrong schema. The application then refused to start
    with a message telling the operator to set an environment variable --
    correct, but a poor answer to "I put it in the documented place".

    So the file is read here too, with the same precedence pydantic-settings
    uses: a real environment variable wins, then ``.env``, then the default.
    Nothing is written back into ``os.environ`` -- this reads the file, it does
    not take over the process's configuration.
    """
    from_env = os.environ.get("DB_SCHEMA")
    if from_env:
        return from_env

    try:
        from dotenv import dotenv_values
    except ImportError:  # pragma: no cover - python-dotenv is a dependency
        return "browser"

    # The same two locations `Settings` looks in, in the same order.
    for candidate in (Path(__file__).resolve().parent.parent.parent / ".env", Path(".env")):
        try:
            if candidate.is_file():
                value = (dotenv_values(candidate) or {}).get("DB_SCHEMA")
                if value:
                    return value.strip().strip("\"'")
        except OSError:  # pragma: no cover - unreadable file is not fatal
            continue
    return "browser"


#: A process serves exactly one schema, so this is a deployment constant rather
#: than a runtime setting. ``db.engine.create_engine`` refuses to start if
#: ``Settings.db_schema`` disagrees with it, because the failure mode otherwise
#: is silent and awful: tables created in one schema while queries read another.
DEFAULT_SCHEMA = _schema()

NAMING_CONVENTION = {
    "ix": "ix_%(column_0_N_label)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s",
    "pk": "pk_%(table_name)s",
}

metadata_obj = MetaData(schema=DEFAULT_SCHEMA, naming_convention=NAMING_CONVENTION)


class Base(DeclarativeBase):
    metadata = metadata_obj


def utcnow() -> datetime:
    """Timezone-aware "now".

    ``datetime.utcnow()`` returns a *naive* datetime, which psycopg then binds
    to a ``timestamptz`` column by assuming it is local time -- an off-by-hours
    bug that only shows up outside UTC. Always aware, always UTC.
    """
    return datetime.now(timezone.utc)


def new_id() -> str:
    return uuid.uuid4().hex


def iso(value: datetime | None) -> str | None:
    """Render a stored timestamp the way the HTTP API has always rendered it.

    Columns are real ``timestamptz`` so the database can compare and index
    them, but every JSON response the frontend already parses expects an
    ISO-8601 string. Converting at this one boundary keeps the wire contract
    unchanged while the storage type improves.
    """
    if value is None:
        return None
    if value.tzinfo is None:
        value = value.replace(tzinfo=timezone.utc)
    return value.astimezone(timezone.utc).isoformat()


# --- shared column shapes --------------------------------------------------
# mapped_column() returns a fresh object per call, so these are factories
# rather than module-level singletons: reusing one Column across two tables
# raises at mapper-configuration time.


def id_column():
    return mapped_column(String(32), primary_key=True, default=new_id)


def created_at_column():
    return mapped_column(DateTime(timezone=True), nullable=False, default=utcnow)
