"""Declarative base, shared column types, and the naming convention.

Two decisions here are worth stating, because both are hard to change later.

**Everything lives in one named schema** (``browser`` by default), not in
``public``. A named schema lets this application share a database with others
without a table-name collision, and makes "drop everything this app owns" a
single statement -- which is what the test harness relies on.

**Constraints are named by convention.** Alembic can only emit
``ALTER TABLE ... DROP CONSTRAINT`` for a constraint it can name, and Postgres
autogenerates names that differ from SQLAlchemy's guesses. Without the
convention below, autogenerated downgrades silently produce SQL that fails on
the day you need it.
"""

from __future__ import annotations

import os
import uuid
from datetime import datetime, timezone

from sqlalchemy import DateTime, MetaData, String
from sqlalchemy.orm import DeclarativeBase, mapped_column

#: The schema every table lives in.
#:
#: Read from the environment at *import* time, because SQLAlchemy binds the
#: schema into ``MetaData`` when the model classes are defined -- long before
#: any ``Settings`` object exists. A process serves exactly one schema, so this
#: is a deployment constant rather than a runtime setting, and
#: ``db.engine.create_engine`` refuses to start if ``Settings.db_schema``
#: disagrees with it. That check exists because the failure mode otherwise is
#: silent and awful: tables created in one schema while queries read another.
DEFAULT_SCHEMA = os.environ.get("DB_SCHEMA", "browser")

NAMING_CONVENTION = {
    "ix": "ix_%(column_0_N_label)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s",
    "pk": "pk_%(table_name)s",
}

metadata_obj = MetaData(schema=DEFAULT_SCHEMA, naming_convention=NAMING_CONVENTION)


class Base(DeclarativeBase):
    metadata = metadata_obj


def utcnow() -> datetime:
    """Timezone-aware "now".

    ``datetime.utcnow()`` returns a *naive* datetime, which psycopg then binds
    to a ``timestamptz`` column by assuming it is local time -- an off-by-hours
    bug that only shows up outside UTC. Always aware, always UTC.
    """
    return datetime.now(timezone.utc)


def new_id() -> str:
    return uuid.uuid4().hex


def iso(value: datetime | None) -> str | None:
    """Render a stored timestamp the way the HTTP API has always rendered it.

    Columns are real ``timestamptz`` so the database can compare and index
    them, but every JSON response the frontend already parses expects an
    ISO-8601 string. Converting at this one boundary keeps the wire contract
    unchanged while the storage type improves.
    """
    if value is None:
        return None
    if value.tzinfo is None:
        value = value.replace(tzinfo=timezone.utc)
    return value.astimezone(timezone.utc).isoformat()


# --- shared column shapes --------------------------------------------------
# mapped_column() returns a fresh object per call, so these are factories
# rather than module-level singletons: reusing one Column across two tables
# raises at mapper-configuration time.


def id_column():
    return mapped_column(String(32), primary_key=True, default=new_id)


def timestamp_column(**kwargs):
    return mapped_column(DateTime(timezone=True), **kwargs)


def created_at_column():
    return mapped_column(DateTime(timezone=True), nullable=False, default=utcnow)
