"""initial schema with tenancy, identity, audit and jobs

Deliberately schema-unqualified. ``migrations/env.py`` sets ``search_path`` to
the configured ``DB_SCHEMA`` before running, so these statements land wherever
that points. Writing ``schema='browser'`` here would pin every deployment and
every test to one schema name -- which it did, until a test tried to migrate a
scratch schema and got "relation already exists" from the real one.

Revision ID: 53aa5b4adc8e
Revises: 
Create Date: 2026-08-25 22:03:17.117661
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '53aa5b4adc8e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspaces')),
    sa.UniqueConstraint('slug', name=op.f('uq_workspaces_slug'))
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('credentials_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_users_workspace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_index('ix_users_workspace', 'users', ['workspace_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.String(length=32), nullable=True),
    sa.Column('actor_email', sa.String(length=320), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_log_actor_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_audit_log_workspace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index('ix_audit_log_resource', 'audit_log', ['resource_type', 'resource_id'], unique=False)
    op.create_index('ix_audit_log_workspace_created', 'audit_log', ['workspace_id', 'created_at'], unique=False)
    op.create_table('credentials',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slots', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_credentials_owner_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_credentials_workspace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credentials')),
    sa.UniqueConstraint('workspace_id', 'name', name='uq_credentials_workspace_id_name')
    )
    op.create_table('jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=200), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('claimed_by', sa.String(length=100), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status in ('queued','running','succeeded','failed','cancelled')", name=op.f('ck_jobs_status_valid')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_jobs_owner_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_jobs_workspace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs')),
    sa.UniqueConstraint('dedupe_key', name='uq_jobs_dedupe_key')
    )
    op.create_index('ix_jobs_claimable', 'jobs', ['status', 'run_after'], unique=False)
    op.create_index('ix_jobs_workspace_created', 'jobs', ['workspace_id', 'created_at'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.String(length=32), nullable=True),
    sa.Column('task', sa.Text(), nullable=False),
    sa.Column('start_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('steps', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_runs_owner_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_runs_workspace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_runs'))
    )
    op.create_index('ix_runs_workspace_status_created', 'runs', ['workspace_id', 'status', 'created_at'], unique=False)
    op.create_table('usecases',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('source_run_id', sa.String(length=32), nullable=True),
    sa.Column('scripts_enabled', sa.Boolean(), nullable=False),
    sa.Column('scripts_enabled_by', sa.String(length=32), nullable=True),
    sa.Column('scripts_enabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_usecases_owner_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scripts_enabled_by'], ['users.id'], name=op.f('fk_usecases_scripts_enabled_by'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_usecases_workspace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usecases'))
    )
    op.create_index('ix_usecases_workspace_status_updated', 'usecases', ['workspace_id', 'status', 'updated_at'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_sessions_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_user_sessions_token_hash'))
    )
    op.create_index('ix_user_sessions_expires', 'user_sessions', ['expires_at'], unique=False)
    op.create_index('ix_user_sessions_user', 'user_sessions', ['user_id'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('mime', sa.String(length=100), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_artifacts_run_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_artifacts_workspace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifacts'))
    )
    op.create_index('ix_artifacts_run_seq', 'artifacts', ['run_id', 'seq'], unique=False)
    op.create_table('batches',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.String(length=32), nullable=True),
    sa.Column('usecase_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('succeeded', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.String(length=32), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_batches_owner_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usecase_id'], ['usecases.id'], name=op.f('fk_batches_usecase_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_batches_workspace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_batches'))
    )
    op.create_index('ix_batches_workspace_usecase_created', 'batches', ['workspace_id', 'usecase_id', 'created_at'], unique=False)
    op.create_table('events',
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_events_run_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id', 'seq', name=op.f('pk_events'))
    )
    op.create_index('ix_events_run_seq', 'events', ['run_id', 'seq'], unique=False)
    op.create_table('usecase_versions',
    sa.Column('usecase_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_by_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_usecase_versions_created_by_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usecase_id'], ['usecases.id'], name=op.f('fk_usecase_versions_usecase_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usecase_id', 'version', name=op.f('pk_usecase_versions'))
    )
    op.create_table('executions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('batch_id', sa.String(length=32), nullable=True),
    sa.Column('usecase_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=True),
    sa.Column('row_index', sa.Integer(), nullable=True),
    sa.Column('inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('outputs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('failed_step_id', sa.String(length=64), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('llm_calls', sa.Integer(), nullable=False),
    sa.Column('llm_tokens', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], name=op.f('fk_executions_batch_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usecase_id'], ['usecases.id'], name=op.f('fk_executions_usecase_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_executions_workspace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_executions'))
    )
    op.create_index('ix_executions_batch_row', 'executions', ['batch_id', 'row_index'], unique=False)
    op.create_index('ix_executions_workspace_usecase_created', 'executions', ['workspace_id', 'usecase_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_executions_workspace_usecase_created', table_name='executions')
    op.drop_index('ix_executions_batch_row', table_name='executions')
    op.drop_table('executions')
    op.drop_table('usecase_versions')
    op.drop_index('ix_events_run_seq', table_name='events')
    op.drop_table('events')
    op.drop_index('ix_batches_workspace_usecase_created', table_name='batches')
    op.drop_table('batches')
    op.drop_index('ix_artifacts_run_seq', table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index('ix_user_sessions_user', table_name='user_sessions')
    op.drop_index('ix_user_sessions_expires', table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index('ix_usecases_workspace_status_updated', table_name='usecases')
    op.drop_table('usecases')
    op.drop_index('ix_runs_workspace_status_created', table_name='runs')
    op.drop_table('runs')
    op.drop_index('ix_jobs_workspace_created', table_name='jobs')
    op.drop_index('ix_jobs_claimable', table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('credentials')
    op.drop_index('ix_audit_log_workspace_created', table_name='audit_log')
    op.drop_index('ix_audit_log_resource', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('ix_users_workspace', table_name='users')
    op.drop_table('users')
    op.drop_table('workspaces')
    # ### end Alembic commands ###
