"""record who ran what

Adds the actor to runs, batches and executions. `owner_email` is denormalized
alongside `owner_id` for the same reason `audit_log.actor_email` is: the FK is
ON DELETE SET NULL, so an id alone stops answering "who did this" the moment
the account is removed.

`server_default=''` is required rather than cosmetic -- these tables have rows,
and a NOT NULL column added without one fails outright. Existing rows get a
blank actor, which is honest: nobody recorded who ran them.

Revision ID: a4006c8e38c0
Revises: 53aa5b4adc8e
Create Date: 2026-08-27 11:09:56.992854
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a4006c8e38c0'
down_revision: Union[str, None] = '53aa5b4adc8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batches', sa.Column('owner_email', sa.String(length=320), nullable=False, server_default=''))
    op.add_column('executions', sa.Column('owner_id', sa.String(length=32), nullable=True))
    op.add_column('executions', sa.Column('owner_email', sa.String(length=320), nullable=False, server_default=''))
    op.create_foreign_key(op.f('fk_executions_owner_id'), 'executions', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    op.add_column('runs', sa.Column('owner_email', sa.String(length=320), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'owner_email')
    op.drop_constraint(op.f('fk_executions_owner_id'), 'executions', type_='foreignkey')
    op.drop_column('executions', 'owner_email')
    op.drop_column('executions', 'owner_id')
    op.drop_column('batches', 'owner_email')
    # ### end Alembic commands ###
